server:
  port: 12345
  #servlet:
  #  context-path: /kytms-business

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  application:
    name: jwxt-teacher #指定服务名

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/kytms/*/mapper/*.xml

ftp:
  host: 192.168.5.210
  port: 22
  username: root
  password: dmcn@123

eureka:
  client:
    service-url:
      # 当需要注册到多个服务中时通过 , 分隔服务地址
      defaultZone : http://localhost:56798/eureka/,http://localhost:56799/eureka/
  instance:
    prefer-ip-address: true # 是否显示ip
    instance-id: teacher # 在注册中心中要显示的注册名称（不可以重名）
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html

swagger:
  authorization:
    key-name: token
